### ISSUE TITLE
Swift package resolution fails because binary for iOS SDK 3.7.0 has changed.

### ISSUE THREAD

**Issue by lardieri** [pendo-io/pendo-mobile-sdk#252]
**Platform + Version**
 iOS

**SDK Version**
3.7.0

**Framework**
Native

**Describe the bug**
The fix for #250 has not been published according to Semantic Versioning standards. You kept version "3.7.0" but changed the underlying binary.

Once you have published a release, you can't change it. If you make a change, you need to increment the version number. **You can't reuse "3.7.0", you need to use "3.7.1" instead.**

Swift Package Manager enforces this:

```
Revision 4ba03d858f17f41c596cbfd31f50b306cc9a4b1c for pendo-mobile-sdk remoteSourceControl https://github.com/pendo-io/pendo-mobile-sdk version 3.7.0 does not match previously recorded value f29a87835669216695a9858b3e833bfbb172d180
```

**To Reproduce**
You can only reproduce this if you had already updated the Swift package in your Xcode project to 3.7.0 prior to the fix for #250.

Simple open Xcode and update the package again. You get the error message quoted above.

**Expected behavior**
Any fix for any issue would increment the version number. In this case, to "3.7.1"

**Logs**
If applicable, please add crash logs OR pendo logs (can be turned on with `PendoManager.shared().setDebugMode(true)`)

**Sample Code**
Code snippet or Sample project

**Additional context**

**Comment by MikePendo** [comment]
@lardieri 
100% right

**Comment by MaximShnirman** [comment]
as we are aware that this might not be best practive, since this version was potentially very problematic and could potentialy block a publish of an app submission to apple, we decided to take this approach to fix the issue.

please remove the package from the project reset package cahces and readd the package. as to our tests this should fix the issue

**Comment by evandcoleman** [comment]
If a version is problematic you can remove that version and release a new one (in this case 3.7.1).

This broke our app as well. Resetting package caches on a local machine is one solution, but it does not resolve issues with CI. This required us to bump the version of our cache key on CircleCI (which is a code change) and blow away the rest of the cache. Certainly not an ideal situation and caused quite the headache for us.
